"""Backend i18n — a tiny, dependency-free server-side translation helper.

Some user-facing text is generated by E.V.'s Python backend and shown
AUTOMATICALLY on the dashboard (the greeting sub-line, the daily/boot briefing,
the status report, and notification banners). This module localizes that text so
it follows the chosen assistant language, mirroring ``ev/core/lang.py`` as the
single source of truth: callers read the language via ``Memory.assistant_lang()``
and pass it to :func:`t` / :func:`plural`.

Design goals: simple, no dependencies, English as the fallback for any missing
language, and the key itself as the last-resort fallback (so a typo degrades
loudly-but-safely instead of crashing). Reusable for the later slice that will
localize the deterministic per-command reply strings.
"""

from __future__ import annotations

from .lang import DEFAULT_LANG, normalize_lang

# Flat catalog: key -> {lang: template}. Templates are ``str.format`` strings.
# English (DEFAULT_LANG) is the fallback for any language missing an entry.
_CATALOG: dict[str, dict[str, str]] = {
    # --- spoken status / dashboard greeting sub-line (overview.spoken_status) ---
    "greeting.morning": {"en": "Good morning", "pt": "Bom dia"},
    "greeting.afternoon": {"en": "Good afternoon", "pt": "Boa tarde"},
    "greeting.evening": {"en": "Good evening", "pt": "Boa noite"},
    "greeting.hello": {"en": "{greeting}, {name}.", "pt": "{greeting}, {name}."},
    "greeting.today_you_have": {
        "en": "Today you have {bits}.",
        "pt": "Hoje você tem {bits}.",
    },
    "greeting.schedule_clear": {
        "en": "Your schedule is clear.",
        "pt": "Sua agenda está tranquila.",
    },
    "greeting.birthday_today": {
        "en": "Today is the birthday of {names}.",
        "pt": "Hoje é aniversário de {names}.",
    },
    "greeting.systems_online": {
        "en": "All systems online. Everything's ready for you.",
        "pt": "Sistemas online. Tudo pronto pra você.",
    },
    "greeting.welcome_back": {
        "en": "Welcome back, {name}. All systems online, everything's ready for you.",
        "pt": "Bem-vindo de volta, {name}. Sistemas online, tudo pronto pra você.",
    },
    "join.and": {"en": "and", "pt": "e"},
    # --- daily briefing (overview.daily_briefing) ---
    "brief.good_morning": {
        "en": "Good morning! Here's your summary for today:",
        "pt": "Bom dia! Aqui vai seu resumo de hoje:",
    },
    "brief.open_tasks": {"en": "Open tasks:", "pt": "Tarefas em aberto:"},
    "brief.reminders": {"en": "Reminders:", "pt": "Lembretes:"},
    "brief.calendar": {"en": "Calendar:", "pt": "Agenda:"},
    "brief.unread_emails": {"en": "Unread emails:", "pt": "E-mails não lidos:"},
    "brief.birthdays_today": {"en": "Birthdays today:", "pt": "Aniversários hoje:"},
    "brief.nothing": {
        "en": "Nothing on the list. Free day — enjoy!",
        "pt": "Nada na lista. Dia livre — aproveita!",
    },
    "brief.weather": {"en": "Weather:", "pt": "Clima:"},
    "brief.news": {"en": "News:", "pt": "Notícias:"},
    # --- status report (web/context.status_text) ---
    "status.title": {"en": "🩺 E.V. Status", "pt": "🩺 Status da E.V."},
    "status.disk": {
        "en": "Disk: {pct}% · {free} GB free",
        "pt": "Disco: {pct}% · {free} GB livres",
    },
    "status.memory": {"en": "Memory: {pct}%", "pt": "Memória: {pct}%"},
    "status.database": {
        "en": "Database: {state} ({size} MB)",
        "pt": "Banco: {state} ({size} MB)",
    },
    "status.keys_header": {
        "en": "Keys / integrations:",
        "pt": "Chaves / integrações:",
    },
    "status.ok": {"en": "ok", "pt": "ok"},
    "status.error": {"en": "error", "pt": "erro"},
    "status.no": {"en": "no", "pt": "não"},
    # --- dashboard notification banners (web/routes/notifications) ---
    "notif.sub_due_title": {
        "en": "Subscription due soon",
        "pt": "Assinatura vencendo em breve",
    },
    "notif.sub_due_body": {
        "en": "{description} — R$ {amount} · due in {days}",
        "pt": "{description} — R$ {amount} · vence em {days}",
    },
    "notif.budget_over_title": {"en": "Budget exceeded", "pt": "Orçamento estourado"},
    "notif.budget_warn_title": {
        "en": "Budget near limit",
        "pt": "Orçamento perto do limite",
    },
    "notif.budget_body": {
        "en": "{category}: R$ {spent} of R$ {amount} ({pct}%)",
        "pt": "{category}: R$ {spent} de R$ {amount} ({pct}%)",
    },
}

# Pluralized fragments: key -> {lang: (singular, plural)}. Both en and pt use the
# same rule here (n == 1 -> singular, else plural), which covers 0/2+ correctly.
_PLURALS: dict[str, dict[str, tuple[str, str]]] = {
    "count.tasks": {"en": ("{n} task", "{n} tasks"), "pt": ("{n} tarefa", "{n} tarefas")},
    "count.reminders": {
        "en": ("{n} reminder", "{n} reminders"),
        "pt": ("{n} lembrete", "{n} lembretes"),
    },
    "count.days": {"en": ("{n} day", "{n} days"), "pt": ("{n} dia", "{n} dias")},
}


def t(lang: str | None, key: str, **kwargs) -> str:
    """Translate ``key`` into ``lang`` (``"en"``/``"pt"``), formatting kwargs.

    Falls back English -> the key itself, and never raises on a missing/extra
    format field (returns the raw template instead)."""
    lang = normalize_lang(lang)
    entry = _CATALOG.get(key)
    if entry is None:
        return key
    template = entry.get(lang) or entry.get(DEFAULT_LANG) or key
    if not kwargs:
        return template
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template


def plural(lang: str | None, key: str, n: int) -> str:
    """Pick the singular/plural form for ``n`` and format ``{n}`` into it."""
    lang = normalize_lang(lang)
    entry = _PLURALS.get(key)
    if entry is None:
        return str(n)
    forms = entry.get(lang) or entry.get(DEFAULT_LANG)
    template = forms[0] if n == 1 else forms[1]
    return template.format(n=n)
